name: Repository validation

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: "ubuntu-latest"
    name: Validate
    steps:
        - uses: actions/checkout@v4

        - name: HACS validation
          uses: hacs/action@main
          with:
            category: integration
            ignore: brands

        - name: Hassfest validation
          uses: home-assistant/actions/hassfest@master

  pre-commit:
    runs-on: ubuntu-latest
    name: Run pre-commit checks
    steps:
        - uses: actions/checkout@v4
        - uses: pre-commit/action@v3.0.1
  ruff:
    runs-on: ubuntu-latest
    name: Run ruff check
    steps:
        - uses: actions/checkout@v4
        - uses: astral-sh/ruff-action@v3
